#!/usr/bin/env python3
# GNU `tac` for hosts that lack it (macOS): the lines of the named files, or of stdin, last first.
import sys

data = b"".join(open(a, "rb").read() for a in sys.argv[1:]) if sys.argv[1:] else sys.stdin.buffer.read()
lines = data.split(b"\n")
tail = lines.pop()
if tail != b"":
    lines.append(tail)
    sys.stdout.buffer.write(b"\n".join(reversed(lines)))
else:
    sys.stdout.buffer.write(b"".join(l + b"\n" for l in reversed(lines)))
